### ISSUE TITLE
Discretization options are insufficient

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#13]
One can control the parameters `bin_contiuous`, `n_bins`, `quantile_bins` and `use_density` to discretize variables.
To my understanding, all variables are then discretized using the same options.

This, however, does not suffice:
1. in most cases, variables need to be discretized differently. 
2. there need to be more options than these few.

In other words: the user needs full control over the discretization settings.

We have a few options here (non exhaustive list):
1. submit a second dataset which contains the discretized values
2. submit a collection of discretization functions 

Which other options can you think of? Which would you prefer?

**Comment by fkoehne** [comment]
A set of discretizer algorithms chosen per case through some kind of hyper-parameter tuning? However, just switching everything to the FUSINTER algorithm @Butterwars favours would probably help to treat columns individually.

**Comment by TobiasGoerke** [comment]
I got this wrong. Apparently, a discretized dataset can be specified. The parameters are an additional option, if no such dataset is specified. I'd vote for this functionality to be moved elsewhere, so that only a discretized dataset can be specified. 

See #20 for new issue
