### ISSUE TITLE
Move discretization to own class

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#20]
`bin_contiuous`, `n_bins`, `quantile_bins` and `use_density` should be moved elsewhere and produce a discretized dataset that can then be passed to anchors.

**Comment by MagdalenaLang1** [comment]
discretization not part of anchors anymore: check branch

**Comment by TobiasGoerke** [comment]
Great changes, well done!
IMO this is the way to go for defining discretizations within anchorsOnR
