### ISSUE TITLE
Extend parameters

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#21]
Parameters such as tau etc. should be specifiable

**Comment by TobiasGoerke** [comment]
Blocked until we can access the Java implementation

**Comment by thllwg** [comment]
Parameters are added, once the issues with the new .jar file are fixed uncomment the corresponding lines in connections.R and switch the .jar for the new version to let it run.

**Comment by TobiasGoerke** [comment]
Enabled by [adapters merge](https://github.com/viadee/javaAnchorAdapters/commit/298d32ce94ebc4c36a006a3705afd7083180407c)
