### ISSUE TITLE
Comments and cleaning of perturbation code needed

### ISSUE THREAD

**Issue by MagdalenaLang1** [viadee/anchorsOnR#22]
in RPerturbFun_tabular_featureless(Disc): parameter perturbFun in RPerturbFun_tabular_featureless(Disc) not used
input not needed? or rather: should be used...

**Comment by MagdalenaLang1** [comment]
not a bug, but required for redirection to method
very "complex" implementation for that purpose, what is the additional functionality? perturbation implementation hard to understand

**Comment by TobiasGoerke** [comment]
Additionally: there are 9 classes that are related and dedicated to perturbations. 
IMO we can and shoukd kill at least 6-7 of them

**Comment by thllwg** [comment]
Code will be refactored for 1.0.0
