### ISSUE TITLE
Diabetes examples shows only 'NA' values in printed explanation

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#26]
Further investigation required

**Comment by MagdalenaLang1** [comment]
@TobiasGoerke: wanted to fix it - but realized I cannot recreate the problem. works for me. specific instances, for which it does not work? coverage=? happens, but coverage needs fixing in general?

**Comment by MagdalenaLang1** [comment]
Alles klar, fixe das Beispiel. problem: training set statt komplettem wird übergeben
