### ISSUE TITLE
Alternatives for busy waiting

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#27]
AnchorsOnR is currently waiting busily for responses. Is this best practice?

**Comment by thllwg** [comment]
This is actually the standard in R. The `socketConnections` supported by R are quite limited, for example `UDP` streams are not supported. However, this problem can be avoided by writing a corresponding client in `C` and integrating it via `Rcpp`. Defining an alternative behavior for `socketConnection` in `C` is a procedure that would also be open to us here. But for now I doubt that this is necessary and plead for accepting the busy waiting.
