### ISSUE TITLE
Target variable has to be in last column of dataset

### ISSUE THREAD

**Issue by MagdalenaLang1** [viadee/anchorsOnR#34]
should not be restricted like that

**Comment by TobiasGoerke** [comment]
I'd like to have this functionality implemented before writing the chapter, as the target column is to be passed by the user and is part of the interface.

**Comment by thllwg** [comment]
The target column can be at an arbitrary position now. However, `buildBins`will ask for the feature column indices and the user has to keep in mind to add +1 to the feature column indice that comes after the target column.

**Comment by TobiasGoerke** [comment]
Idea: We could also create bins based on column names
