### ISSUE TITLE
Enable true model agnostic (i.e. technology agnostic) behavior

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#37]
AnchorsOnR is currently limited to a certain type of model (mlr/h2o).
Can we make this more generic or implement an own interface that the user can use?

**Comment by TobiasGoerke** [comment]
Additionally: refactor models.R. 
These methods should only need to return a vector of responses. Truth values do not matter!

**Comment by fkoehne** [comment]
Yeah. Greetings from sunny Münster at 12° C. :)
