### ISSUE TITLE
Visualization required

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#4]
We need a visualization that is independent from ggplot

**Comment by MagdalenaLang1** [comment]
added a simple one - maybe enough for a first version?

**Comment by fkoehne** [comment]
Could you provide an example here?

**Comment by TobiasGoerke** [comment]
This is what visualization by @thllwg originally looked like (might provide a point of reference to compare new methods to).

![anchors visualization](https://user-images.githubusercontent.com/13769461/62514648-21f9e400-b820-11e9-9679-72ffd5e43b1c.png)

**Comment by MagdalenaLang1** [comment]
The current status: features refering to the same attribute are in one column (and only the attributes with at least one anchor are shown). Hight per bar provides feature weight (also the color, could reduce to one. at moment, color is alternative to y-axis). Nothing fancy - especially when too many instances have to be shown. 
![examplePlot](https://user-images.githubusercontent.com/53171677/62521328-bb7cc200-b82f-11e9-93cf-cd78518cdc2a.png)

**Comment by TobiasGoerke** [comment]
Notes: 
- Show explained outcome/target of instance
- Include notion of coverage

**Comment by MagdalenaLang1** [comment]
Alternative suggestion, considering the notes from skype discussion. the width of a bar represents the coverage, which is also provided as number on the right side of a bar

obvious TODO: bin label for small bar-sections
another TODO: minimum width of a bar
![testPlot3instances](https://user-images.githubusercontent.com/53171677/62557787-f30f5c80-b877-11e9-9fbc-ec9af5ae5d3f.png)

**Comment by TobiasGoerke** [comment]
Simple, yet great and intuitive visualization. I very much like this approach. IMO we should stick with it and see if we can further improve it.

**Comment by fkoehne** [comment]
Nice. This looks like the terrain color scheme? Since Tobias does not want to comment on colouring - what about more contrastive colours like c("#DFAD47","#7EBCA9", "#E5344E")? ;)

**Comment by TobiasGoerke** [comment]
I am considering this done. Plots are customizable and look great. I'd say sufficient for our first release.

![grafik](https://user-images.githubusercontent.com/13769461/63003000-8697ed00-be77-11e9-90e0-17a960bea38c.png)
