### ISSUE TITLE
Evaluate alternative discretizers

### ISSUE THREAD

**Issue by fkoehne** [viadee/anchorsOnR#44]
Preferable CRAN-hosted packages with no or few options and with a non-GPL license from your existing short-list. :)

**Comment by MarvinBleier** [comment]
Currently all discretization packages that i could find have the **GPL-Licence.** For unsupervised discretization there are: arules, classInt, infotheo, discretization, dprep (deprecated)

For supervised: discretization, dprep

https://cran.r-project.org/web/packages/classInt/classInt.pdf
https://cran.r-project.org/web/packages/infotheo/infotheo.pdf
https://cran.r-project.org/web/packages/discretization/discretization.pdf
https://mran.microsoft.com/snapshot/2017-02-20/web/packages/dprep/dprep.pdf
https://cran.r-project.org/web/packages/arules/arules.pdf

I could not find an R-implentation of the promising **FUSINTER** algorithm at all. Ameva is in the  '_discretization_' package. Other supervised discretization in the packages above are _CAIM_, _CACC_ and _Chi²-based_ algorithms.

**Comment by fkoehne** [comment]
Looks like a gap to me. 
Thanks!
