### ISSUE TITLE
Deserialization ordering

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#61]
When printing or plotting rules predicates are not necessarily in the right order, i.e., as anchors constructed or assembled them.
This should be fixed

**Comment by fkoehne** [comment]
Thank you - is the Milestone still correct?

**Comment by TobiasGoerke** [comment]
I've closed 1.0.0 iml-book and moved the remaining issue to 1.0.1 CRAN release, as the iml book chapter has been published.
For me, the milestones are still accurate and comprise what we should do next to be able to submit anchorsOnR to CRAN.
Feel free to change the prioritization as you see fit.
