### ISSUE TITLE
isInIntervall fails to recognize intervall boundaries

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#8]
`IsInIntervall("2.9",c("[2,2.9)","[2.9,3.2]") `returns `TRUE TRUE`

**Comment by TobiasGoerke** [comment]
@Ronjakoehling zugewiesen auf Wunsch von @thllwg

**Comment by MagdalenaLang1** [comment]
I will work on it - fix it together with discretization-topic (probably other data-format..)

**Comment by MagdalenaLang1** [comment]
not used anymore - at the moment (see discretization branch)

**Comment by TobiasGoerke** [comment]
So, can this issue be closed upon merging the branch?
