### ISSUE TITLE
Include Cervical Cancer Set explanation

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/anchorsOnR#9]

**Comment by MagdalenaLang1** [comment]
added example. allowing comparability with java example and "better" discretization variant, compare relevant other issues.

**Comment by MagdalenaLang1** [comment]
use this for chapter? need better discretization?

**Comment by TobiasGoerke** [comment]
I consider this example done! :) 
The example will be further developed out of this project's scope.
